#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "\n🔥 Running pre-commit hook..."

# Run lint-staged (prettier, eslint)
echo "\n✨ Checking code style and linting..."
npx lint-staged -v

# Check typescript types
echo "\n🤓 Checking typescript types..."
yarn check:types

echo "\n🎉 Pre-commit hook succesful! Commiting your changes now.\n"
